[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    chris--a/Keypad@^3.1.1
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -std=gnu++17

monitor_filters =
    esp32_exception_decoder
    colorize
    time